### ISSUE TITLE
Feature Request :D

### ISSUE THREAD

**Issue by jxsl13** [timur-tabi/kickstarter-pledge-watch#10]
How about adding the possibility to choose cheaper pledges when they become available?
Like I have pledged for something worth 80 $, but there are two more possibilities to choose a cheaper "early bird" pledge. If one cheaper pledge is available, the script changes my pledge to the cheaper one. If the cheapest one is available the script changes to the cheapest one, but if a more expensive one after the cheapest is available, the script should not change to the more expensive one.
Nice would be to be able to add pledges to a list (order from cheapest to most expensive), from which the script can check whether to change the pledge to the cheaper one or not.

**Comment by timur-tabi** [comment]
I don't understand this request.  The script scans any pledges you give it, so if you tell it to scan for the cheaper pledge, it will notify you when that pledge becomes available.

**Comment by jxsl13** [comment]
If you have more than one cheaper pledge available,  yet already none left
for you to pledge for,  the script could choose the cheaper ones available,
meaning,  more than one chealer pledge to change to.

**Comment by timur-tabi** [comment]
I still don't understand.  Let's say there are three pledge levels available, $60, $80, and $100.  The $100 level is open, but the other two are full.  You've already pledged for the $100 level, but you want to save money and switch to the $60 or $80 level when available.  You tell the script to wait for the $60 and $80 levels.  When either becomes available, you get notified and can pledge for them.

What's wrong with that?

**Comment by jxsl13** [comment]
I would have to have two scripts running ,  don't I?
Does the script only notify ot change the perk on its own Oo?

**Comment by highvoltag3** [comment]
@timur-tabi that's is not clear in your READ.MD which is probably why @jxsl13 had that question, I was wondering the same but then I read the code and noticed it took multiple pledges. In my fork I actually modified the documentation to state that and added an example for it.

**Comment by timur-tabi** [comment]
Ok, I will update the documentation next time I work on this project.  Or if you like, submit a patch.

**Comment by highvoltag3** [comment]
:+1: Great job BTW thank you very much for you're awesome script 😀
