### ISSUE TITLE
Violation against ToS

### ISSUE THREAD

**Issue by SirWindfield** [timur-tabi/kickstarter-pledge-watch#11]
As stated here:
> (v) use manual or automated software, devices, or other processes to "crawl" or "spider" any page of the Site.

Your script does by definition "spider" web pages, meaning you are extracting information from webpages to process those later on.

**Comment by timur-tabi** [comment]
To me, "spider" means to extract information from multiple web pages, not just one.  I'm not downloading every Kickstarter project page.

Besides, if you don't like it, don't use the script.

**Comment by SirWindfield** [comment]
I do not want to be offensive in any way. I just wanted to let you know that by pure definition found on Wikipedia and in dictionaries it is one. That's all.
