### ISSUE TITLE
Kickstarter was updated and the watch is not working anymore

### ISSUE THREAD

**Issue by czm97176** [timur-tabi/kickstarter-pledge-watch#12]
Kickstarter was updated and the watch is not working anymore

**Comment by timur-tabi** [comment]
Works for me:

```
$ ./kswatch.py https://www.kickstarter.com/projects/gonab/tao-long
1. $17 Early Bird - Tao Long Retail
2. $28 Early Bird - Tao Long Deluxe
3. $100 Tao Long Numbered Collectors Bundle

Select pledge levels: 
```

Can you show me the failure you're seeing.

**Comment by czm97176** [comment]
Yes, there is some several pledge is work but except one , i don't know why. Would you please help ?
https://www.kickstarter.com/projects/tiffencompany/steadicam-volt-smartphone-stabilizer-shake-free-vi

**Comment by timur-tabi** [comment]
Ok, that project breaks on my script.  I will try to fix it.

**Comment by timur-tabi** [comment]
Ah, the script is working properly.  There's only one award available, and so it selects it for you automatically.  The problem is that it doesn't say anything, and so it appears to be broken.

I've added a chance to make it more verbose, and that should resolve this problem for you.
