### ISSUE TITLE
Still doesn't work 100%

### ISSUE THREAD

**Issue by amchang** [timur-tabi/kickstarter-pledge-watch#4]
https://www.kickstarter.com/projects/meld/meld-a-perfect-meal-every-time

I tried to dig in your code bit but not sure where it fails. For this project, it has something in the right HTML bar (Featured section) which causes the script to fail. Not sure where in the code you need to ignore everything else but rewards.

**Comment by timur-tabi** [comment]
I found the bug.  A fix is coming soon.
