### ISSUE TITLE
No unavailable limited rewards for this Kickstarter

### ISSUE THREAD

**Issue by ketz** [timur-tabi/kickstarter-pledge-watch#6]
Trying to monitor a project that is currently live, but I keep getting "No unavailable limited rewards for this Kickstarter" as an error, with the latest version of the script.

The URL I'm trying with is as follows:
https://www.kickstarter.com/projects/812287807/thousand-finally-a-bike-helmet-youd-actually-want

Any thoughts?

**Comment by timur-tabi** [comment]
Fixed.  Thanks for catching this.
