### ISSUE TITLE
Errors for me when not specifying a pledge amount.

### ISSUE THREAD

**Issue by biship** [timur-tabi/kickstarter-pledge-watch#7]
E:\Downloads\kickstarter-pledge-watch-master>kswatch.py  https://www.kickstarter.com/projects/1062682568/umbra
Traceback (most recent call last):
  File "E:\Downloads\kickstarter-pledge-watch-master\kswatch.py", line 191, in <module>
    selected = pledge_menu(rewards)
  File "E:\Downloads\kickstarter-pledge-watch-master\kswatch.py", line 145, in pledge_menu
    print '%u. $%u %s' % (i + 1, rewards[i][0], rewards[i][4][:70])
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 14: character maps to <undefined>

**Comment by timur-tabi** [comment]
Either this was a one-time fluke, or it's a Windows-specific problem, because it works for me on Linux:

$ ./kswatch.py https://www.kickstarter.com/projects/1062682568/umbra
1. $9 WARRIOR – CRAZY EARLY BIRDEverything above ♦ Get a digital copy of Umb
2. $12 WARRIOR – EARLY BIRDEverything above (Except for Crazy Early Bird tier
3. $90 BISHOP – EARLY BIRDEverything above (Except for Limited tiers) ♦ SIGNE

Select pledge levels:

**Comment by biship** [comment]
Hmmm so it works for some projects and not others. Possibly a UTF encoding thing. 

Working:
E:\Downloads\kickstarter-pledge-watch-master>kswatch.py https://www.kickstarter.com/projects/iga/bloodstained-ritual-of-the-night
1. $800 SIGNED AMANO PRINTThe poster included with the Collectors Box will be
2. $950 SIGNED AMANO PRINT IIThe poster included with the Collectors Box will
3. $1500 ANCESTRAL BLOODLINEThe development team will create a digital portrait
4. $1550 ANCESTRAL BLOODLINE IIThe development team will create a digital portr
5. $1600 ANCESTRAL BLOODLINE IIIThe development team will create a digital port
6. $2000 RUNIC FORGINGCollaborate with the development team to create an in-gam
7. $3000 UNLEASH THE HOUNDS OF HELLThe development team will turn your pet (or

Select pledge levels: 


Not Working:
E:\Downloads\kickstarter-pledge-watch-master>kswatch.py  https://www.kickstarter.com/projects/1062682568/umbra
Traceback (most recent call last):
  File "E:\Downloads\kickstarter-pledge-watch-master\kswatch.py", line 191, in <module>
    selected = pledge_menu(rewards)
  File "E:\Downloads\kickstarter-pledge-watch-master\kswatch.py", line 145, in pledge_menu
    print '%u. $%u %s' % (i + 1, rewards[i][0], rewards[i][4][:70])
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 14: character maps to <undefined>

**Comment by biship** [comment]
I guess not big deal as it works when passing an amount on the command line. Just letting you know about this error :)

**Comment by timur-tabi** [comment]
Can you try inserting 
    sys.stdout.encoding='utf-8'

around line 32, and see if that helps?

**Comment by timur-tabi** [comment]
Also, let me know if
sys.stdout.errors = 'replace'
works

**Comment by biship** [comment]
E:\Downloads\kickstarter-pledge-watch-master>kswatch.py https://www.kickstarter.com/projects/1062682568/umbra
Traceback (most recent call last):
  File "E:\Downloads\kickstarter-pledge-watch-master\kswatch.py", line 32, in <module>
    sys.stdout.encoding='utf-8'
TypeError: readonly attribute

**Comment by timur-tabi** [comment]
Alright, I'll have to research this later.

**Comment by p1r473** [comment]
add this to your import statements

import codecs
sys.stdout = codecs.getwriter('utf8')(sys.stdout)

**Comment by biship** [comment]
Nice. That seems to have fixed it (except for the ugly characters).

E:\Downloads\kickstarter-pledge-watch-master>kswatch.py https://www.kickstarter.com/projects/1062682568/umbra
1. $9 WARRIOR ΓÇô CRAZY EARLY BIRDEverything above ΓÖª Get a digital copy of Umb
2. $12 WARRIOR ΓÇô EARLY BIRDEverything above (Except for Crazy Early Bird tier
3. $90 BISHOP ΓÇô EARLY BIRDEverything above (Except for Limited tiers) ΓÖª SIGNE

Select pledge levels:

**Comment by p1r473** [comment]
A lot of these have already been fixed in forks of this project
urahara-san / kickstarter-pledge-watch-and-manage
birla / kickstarter-pledge-watch-and-manage

**Comment by p1r473** [comment]
I just learned to accept the ugly characters until someone finds a better fix :)

**Comment by timur-tabi** [comment]
Can you test this change and let me know if this also fixes the problem?  If so, I will commit it.

@@ -128,7 +128,7 @@ class KickstarterHTMLParser(HTMLParser.HTMLParser):
         if self.in_remaining_block:
             self.remaining += data
         if self.in_desc_block:
-            self.description += self.unescape(data)
+            self.description += self.unescape(data).encode('ascii','ignore')
 
     def result(self):
         return self.rewards

**Comment by biship** [comment]
I can't test on Umbra any more as the kickstarter finished.

I tried on:
kswatch.py https://www.kickstarter.com/projects/inxile/the-bards-tale-iv
No unavailable limited rewards for this Kickstarter

However the page shows
Pledge $20 or more
15,000 backers 
All gone!

**Comment by timur-tabi** [comment]
This works for me.

$ ./kswatch.py https://www.kickstarter.com/projects/inxile/the-bards-tale-iv
1. $20 EARLY BARD GETS THE WYRMTHE BARDS TALE IV as a digital download for Wi
2. $95 PREMIER COLLECTORS EDITION - EARLY BARDA HIGH-QUALITY PREMIUM COLLECTO
3. $650 SUPREME BOX COLLECTORFor the collector who just cant get enough stuff 

I think it may have been a fluke.  That is, at the time you ran the script, the $20 pledge level was available.  But a minute later when you went to the web site, it was already taken.
